# coding: utf-8

"""
    A parser rest-API for EDIFACT MSCONS messages (energy sector, DE/AT/CH)

    This [OpenAPI-Spezifikation](https://www.openapis.org/) describes the Rest-API of the EDIFACT MSCONS parser,
    based on version [2.4c](https://bdew-mako.de/linkPdf/9645).

    The version of the OpenAPI document: 2.4c.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501
import logging.config

from fastapi.responses import RedirectResponse

from msconsparser.adapters.inbound.rest import main
from msconsparser.adapters.inbound.rest.impl.health_check_routers import router as HealthChecksApiRouter
from msconsparser.adapters.inbound.rest.impl.lifespan_events import startup_lifespan
from msconsparser.infrastructure.logging_config import get_logging_config

logging.config.dictConfig(get_logging_config())

app = main.app

# Add event handler during application startup
app.add_event_handler("startup", startup_lifespan)

# Make a redirect to the swagger-ui docs when accessing the base url
@app.get("/", include_in_schema=False)
async def docs_redirect() -> RedirectResponse:
    return RedirectResponse(url=str(app.docs_url))

app.include_router(HealthChecksApiRouter)
